### ISSUE TITLE
Ну где же обещанный код???

### ISSUE THREAD

**Issue by RooTooZ** [liff4/fias#1]

**Comment by RooTooZ** [comment]
Почему закрыли без всяких объяснений?

2014-06-12 13:18 GMT+04:00 Alexander Lebedev notifications@github.com:

**Comment by liff4** [comment]
Код будет в течении 1-2 месяцев для YII 2

**Comment by RooTooZ** [comment]
Скорее всего не дождусь я вашего кода)

**Comment by ghost** [comment]
Итак, шёл 2015 год ....

**Comment by RooTooZ** [comment]
:+1:

**Comment by SlimSavernake** [comment]
Ну что там?

**Comment by htrv** [comment]
Ну че там?)

**Comment by liff4** [comment]
Sorry, NDA does not allow me to do this. Sо sorry
